### ISSUE TITLE
Add vcn > display_name to oci_core_security_list.

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-oci#137]
**Is your feature request related to a problem? Please describe.**

it would be good to have the VCN name associated to the oci_core_security_list table apart from the vcn_id field to avoid unnecessary joins to get the VCN name associated to the respective security list. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bigdatasourav** [comment]
as discussed , currently there is no parent child relationship present for security list api with vcn table. To have vcn_name in security list table we need to do a separate api call which is not a good option.
https://github.com/oracle/oci-go-sdk/issues/298
