### ISSUE TITLE
Extend the current oci_core_subnet to get the flow log details.

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-oci#140]
**Is your feature request related to a problem? Please describe.**
VCN subnet can have the flow log associated if available for the the same region. if we can make attempt to get the same in the subnet table rather than pulling from log service table will be good. At best if we have no API available for the SDK we use, we can raise the request for the same. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bigdatasourav** [comment]
As of now, API is not available in subnet to fetch flowlog. We have to use log table to get flowlog details for subnet.

**Comment by bigdatasourav** [comment]
@ParthaI Could you please check if there is any API available now to fetch the flow log details?

**Comment by ParthaI** [comment]
@bigdatasourav We can filter the FlowLog details from `oci_logging_log` table. Please check the below query. If you need any other details please let me know, Thanks!

```
> select
  name,
  log_group_id,
  log_type,
  is_enabled,
  configuration -> 'source' ->> 'service' as service_type
from
  oci_logging_log
where
configuration -> 'source' ->> 'service' = 'flowlogs';
+--------------+---------------------------------------------------------------------------------------------+----------+------------+--------------+
| name         | log_group_id                                                                                | log_type | is_enabled | service_type |
+--------------+---------------------------------------------------------------------------------------------+----------+------------+--------------+
| subnet_m_all | ocid1.loggroup.oc1.ap-mumbai-1.dabakjdweuheefhje6klimva7j3undfasdhaskdkasbfewbfhewbwebffbeu | SERVICE  | true       | flowlogs     |
+--------------+---------------------------------------------------------------------------------------------+----------+------------+--------------+
```
