### ISSUE TITLE
Add table oci_core_volume_metrics

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-oci#176]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

**Comment by rajlearner17** [comment]
This can be inline with AWS metric e.g. https://hub.steampipe.io/plugins/turbot/aws/tables/aws_ebs_volume_metric_read_ops_daily

**Comment by bigdatasourav** [comment]
https://github.com/turbot/steampipe-plugin-oci/issues/185
https://github.com/turbot/steampipe-plugin-oci/issues/184
