### ISSUE TITLE
CloudGuard tables are returning empty response

### ISSUE THREAD

**Issue by ParthaI** [turbot/steampipe-plugin-oci#278]
**Describe the bug**
If you run the query again and again in 1/3 of the time we will get the error, run the query like
`select * from oci_cloud_guard_detector_recipe;`  then quit the steampipe, run the query again  `select * from oci_cloud_guard_detector_recipe where name = 'OCI Configuration Detector Recipe';` we will get the error 1/3 of the time. 

![Screenshot 2021-08-17 at 12 42 39 PM](https://user-images.githubusercontent.com/47887552/129680558-25e6a608-665a-4dad-a731-96c73393169a.png)

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**
It should response back rows instead of err

**Additional context**

**Comment by bigdatasourav** [comment]
Cloudguard table APIs are returning empty result except the configuration one. Raised the below issue with OCI go sdk team-
https://github.com/oracle/oci-go-sdk/issues/317
