### ISSUE TITLE
Add table oci_database_backup

### ISSUE THREAD

**Issue by bigdatasourav** [turbot/steampipe-plugin-oci#283]
**References**
https://docs.oracle.com/en-us/iaas/Content/Database/Tasks/backingup.htm

**Comment by c0d3r-arnab** [comment]
There is an issue with oci_database_backup. The [documentation](https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/Backup/ListBackups) says `Gets a list of backups based on the databaseId or compartmentId specified. Either one of these query parameters must be provided`. 

In the case of SDK, the following are the findings:
- If we provide only the `compartmentId` in the request URL, the result is not showing `Automatic Backup (incremental Backup, initiated by Auto Backup)` data and shows only the backup created by the user.
- If we provide only the `databaseId` in the request URL, we get an error like this: `Error: Service error:MissingParameter. Missing compartmentId. http status code: 400`.
- If we provide both `compartmentId` and `databaseId` in the request URL, we get an error like this: `Error: Service error:InvalidParameter. databaseId Please provide only one of these parameters – databaseId, compartmentId.. http status code: 400`.

In the case of CLI, the scenarios remain the same with one difference. The difference is, if I perform the list command with only `databaseId`, both backups (initiated by Auto Backup and initiated by User) are displayed in the result.

I also came across this [issue](https://github.com/oracle/oci-cli/issues/333) raised in Github related to `compartmentId`.
