### ISSUE TITLE
oci_database_db_system version is null

### ISSUE THREAD

**Issue by martinberger-ch** [turbot/steampipe-plugin-oci#297]
**Describe the bug**
A query from oci_database_db_system on columns version returns null:

steampipe query "select
   display_name,
   database_edition,
   version
 from
   oci_database_db_system;"
+--------------------+--------------------+---------+
| display_name       | database_edition   | version |
+--------------------+--------------------+---------+
| dbsys-ivz-db-01    | ENTERPRISE_EDITION | <null>  |
| just-4-calculation | STANDARD_EDITION   | <null>  |
| DBSystem-PAGDB     | STANDARD_EDITION   | <null>  |
+--------------------+--------------------+---------+

**Steampipe version (`steampipe -v`)**
steampipe version 0.7.1

**Plugin version (`steampipe plugin list`)**
+--------------------------------------------+---------+---------------------------+
| Name                                       | Version | Connections               |
+--------------------------------------------+---------+---------------------------+
| hub.steampipe.io/plugins/turbot/oci@latest | 0.2.0   | oci_tenant_xxxxxxxx     |
+--------------------------------------------+---------+---------------------------+

**To reproduce**
Just do a query.

**Expected behavior**
Version from db-home should be shown - example command in OCI CLI where ORACLE_HOME version is shown: 

oci db db-home list --compartment-id $COMPARTMENT_ID

{
  "data": [
    {
      "compartment-id": "ocid1.compartment.oc1..aaaaaaaaaql7z6vtbjjjz24lnyxxxf2xxxxxxxxx",
      "database-software-image-id": null,
      "db-home-location": null,
      "db-system-id": "ocid1.dbsystem.oc1.eu-zurich-1.ab5heljriwkcxaxdahcelyjdugsgibwmhxxxxxxxxxx",
      "db-version": "19.11.0.0.0",
      "defined-tags": null,
      "display-name": "dbhome20210607111507",
      "freeform-tags": null,
      "id": "ocid1.dbhome.oc1.eu-zurich-1.ab5heljrtgh5x4fjji75eialxcxe3bu7xwdtxxxxxxx",
      "last-patch-history-entry-id": null,
      "lifecycle-details": null,
      "lifecycle-state": "AVAILABLE",
      "one-off-patches": null,
      "time-created": "2021-06-07T11:15:07.191000+00:00",
      "vm-cluster-id": null
    }
  ]
}

**Additional context**
Please add version here.

**Comment by rajlearner17** [comment]
@martinberger-ch thanks for the continuous feedback, the API call for `oci_database_db_system` contains the version as an attribute, and it's returning null. We have the db_version column in `oci_database_db_home` table, which renders the outcome. We will investigate further and raise this OCI team as well before taking any customization.
                                    `

**Comment by cbruno10** [comment]
@rajlearner17 Have you received any updates from the OCI team yet?

**Comment by rajlearner17** [comment]
@cbruno10 the raised issue **3-26892148051** [CLI returns "version": null, in oci db system list,] got closed with a few rounds of conversation and experiment, we were supposed to provide more details, and it was consuming time. The behaviour remains the same in CLI. We have to re-open the case and experiment further. However `oci_database_db_home` renders expected data. I suggest we close and wait further for any usage & ask for it in future.

**Comment by rajlearner17** [comment]
We will track the OCI SR and take action in future.
