### ISSUE TITLE
Billing Information as Table

### ISSUE THREAD

**Issue by martinberger-ch** [turbot/steampipe-plugin-oci#298]
**Is your feature request related to a problem? Please describe.**
Please add the OCI billing information as Steampipe query in a new table.

**Describe the solution you'd like**
The billing is selectable by day / range-of-days and groupable by
a) tenancy
b) compartment
c) resource type

Example:

_SELECT compartment, sum(costs) 
FROM table_xy_z
WHERE billing_date='2021-08-30'
GROUP BY compartment

SELECT compartment, resource-type, sum(costs) 
FROM table_xy_z
WHERE resource-type ='COMPUTE' 
AND billing_date between '2021-08-01' and '2021-08-01'
GROUP by compartment, resource-type_

**Describe alternatives you've considered**

This is the URL Endpoint where the data can be gathered with OCI login information - example:

_endpoint = 'https://usageapi.eu-frankfurt-1.oci.oraclecloud.com/20200107/usage'
body = {
  'tenantId': 'ocid1.tenancy.oc1..aaaaaaaac3gjl7xgpxu3mmqhabcdteds',
  'timeUsageStarted': (2021-08-26T00:00:00Z),
  'timeUsageEnded':(2021-08-27T00:00:00Z),
  'granularity': 'DAILY'
}_

**Additional context**
See OCI documentation usage AP endpoints:
[https://docs.oracle.com/en-us/iaas/api/#/en/usage/20200107/](https://docs.oracle.com/en-us/iaas/api/#/en/usage/20200107/ )

**Comment by e-gineer** [comment]
Good idea @martinberger-ch :-)

This will leverage the Usage API - https://pkg.go.dev/github.com/oracle/oci-go-sdk@v24.3.0+incompatible/usageapi

**Comment by rajlearner17** [comment]
We are still looking to it and raising an issue to get OCI technical support with SR 3-26892105951 
Both the CLI and AP response returns a set of null values for many key attributes including the tenant-id, compartment-id etc.
```
oci usage-api usage-summary request-summarized-usages --granularity DAILY --tenant-id ocid1.tenancy.oc1..aaaaaaaahnm7gleh5soecxzjetci3yjjnjqmfkr4po3hoz4dsfdsfdsfd--time-usage-ended 2021-09-15T00:00:00.000Z --time-usage-started 2021-08-15T00:00:00.000Z
```
```
{
        "ad": null,
        "compartment-id": null,
        "compartment-name": null,
        "compartment-path": null,
        "computed-amount": 0.1109006376,
        "computed-quantity": 3.240908673768,
        "currency": "SGD",
        "discount": null,
        "is-forecast": false,
        "list-rate": null,
        "overage": null,
        "overages-flag": null,
        "platform": null,
        "region": null,
        "resource-id": null,
        "resource-name": null,
        "service": null,
        "shape": null,
        "sku-name": null,
        "sku-part-number": null,
        "subscription-id": null,
        "tags": [
          {
            "key": null,
            "namespace": null,
            "value": null
          }
        ],
        "tenant-id": null,
        "tenant-name": null,
        "time-usage-ended": "2021-08-16T00:00:00+00:00",
        "time-usage-started": "2021-08-15T00:00:00+00:00",
        "unit": null,
        "unit-price": null,
        "weight": null
      }
```

**Comment by rajlearner17** [comment]
@cbruno10 we had a demo with the OCI team, and this was their response, and they verbally communicated, that this will be with their DEV team, we can check later SDK/CLI releases. 

```
Thu, 23 Sep 2021 08:24:24 UTC
Hello Rajesh,
Thanks for the time over the call, as discussed please check the update on Sept15. This is an expected behavior.
```
The outcome still remains the same.

```
{
  "data": {
    "group-by": null,
    "items": [
      {
        "ad": null,
        "compartment-id": null,
        "compartment-name": null,
        "compartment-path": null,
        "computed-amount": 0.1102670976,
        "computed-quantity": 3.164289690376,
        "currency": "SGD",
        "discount": null,
        "is-forecast": false,
        "list-rate": null,
        "overage": null,
        "overages-flag": null,
        "platform": null,
        "region": null,
        "resource-id": null,
        "resource-name": null,
        "service": null,
        "shape": null,
        "sku-name": null,
        "sku-part-number": null,
        "subscription-id": null,
        "tags": [
          {
            "key": null,
            "namespace": null,
            "value": null
          }
        ],
        "tenant-id": null,
        "tenant-name": null,
        "time-usage-ended": "2022-06-14T00:00:00+00:00",
        "time-usage-started": "2022-06-13T00:00:00+00:00",
        "unit": null,
        "unit-price": null,
        "weight": null
      },
```
