### ISSUE TITLE
Query region sa-vinhedo-1 is returning invalid region

### ISSUE THREAD

**Issue by valdecircarvalho** [turbot/steampipe-plugin-oci#300]
**Describe the bug**
When use steampipe to query OCI region sa-vinhedo-1 is returning error :
_**Error: Connection config have invalid regions: sa-vinhedo-1. Edit your connection configuration file and then restart Steampipe**_

**Steampipe version (`steampipe -v`)**
steampipe version 0.7.1

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0
oci@lastest - 0.2.0
**To reproduce**
Use region sa-vinhedo-1 in the oci.spc config file

**Expected behavior**
Query objects from the region.
I try use the same command for another region and it´s working fine returning what was expecting.
Tried with several commands and all is returning the same error.

**Additional context**
This region is relative new in OCI (2-3 months) and I think something should be changed in to code to consider this region.

Querying oci_region table brings the region.

`> select * from oci_region;
+----------------+-----+----------------+--------+----------------+---------------------------------------------------------------------------------+
| name           | key | is_home_region | status | title          | tenant_id                                                                       |
+----------------+-----+----------------+--------+----------------+---------------------------------------------------------------------------------+
| eu-amsterdam-1 | AMS | false          |        | eu-amsterdam-1 | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| uk-london-1    | LHR | false          |        | uk-london-1    | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| us-ashburn-1   | IAD | false          |        | us-ashburn-1   | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| ap-mumbai-1    | BOM | false          |        | ap-mumbai-1    | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| ap-sydney-1    | SYD | false          |        | ap-sydney-1    | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| ca-montreal-1  | YUL | false          |        | ca-montreal-1  | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| eu-frankfurt-1 | FRA | false          |        | eu-frankfurt-1 | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| ca-toronto-1   | YYZ | false          |        | ca-toronto-1   | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| sa-saopaulo-1  | GRU | false          | READY  | sa-saopaulo-1  | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| me-jeddah-1    | JED | false          |        | me-jeddah-1    | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| sa-vinhedo-1   | VCP | true           | READY  | sa-vinhedo-1   | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| ap-melbourne-1 | MEL | false          |        | ap-melbourne-1 | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| uk-cardiff-1   | CWL | false          |        | uk-cardiff-1   | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| ap-osaka-1     | KIX | false          |        | ap-osaka-1     | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| ap-hyderabad-1 | HYD | false          |        | ap-hyderabad-1 | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| ap-seoul-1     | ICN | false          |        | ap-seoul-1     | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| eu-zurich-1    | ZRH | false          |        | eu-zurich-1    | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| ap-tokyo-1     | NRT | false          |        | ap-tokyo-1     | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| me-dubai-1     | DXB | false          |        | me-dubai-1     | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| sa-santiago-1  | SCL | false          |        | sa-santiago-1  | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| us-phoenix-1   | PHX | false          |        | us-phoenix-1   | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| us-sanjose-1   | SJC | false          |        | us-sanjose-1   | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
| ap-chuncheon-1 | YNY | false          |        | ap-chuncheon-1 | ocid1.tenancy.oc1..aaaaaaaasynhbrdkftfl7d5g5htpijcaw5wm32x3kzgyovhnhbkbx5jvl2kq |
+----------------+-----+----------------+--------+----------------+---------------------------------------------------------------------------------+`

**Comment by e-gineer** [comment]
ah ... interesting, a new region that we missed! Thanks so much for reporting @valdecircarvalho :-)

We maintain a list of "valid regions" in the code at https://github.com/turbot/steampipe-plugin-oci/blob/f0b76cc5e264750373bf63be38a1cdd227e96d2b/oci/multi_region.go#L144

FWIW we keep this list so that we can do wildcard matching on region names in the config file.  Looks like we need to add it there.

As a workaround, I tried adding it explicitly to my config (instead of `*`):

```
connection "oci_tenant_y" {
  plugin                = "oci"
  config_file_profile   = "DEFAULT"          # Name of the profile
  config_path           = "~/.oci/config"    # Path to config file
  regions               = ["ap-mumbai-1" , "us-ashburn-1", "sa-vinhedo-1"] # List of regions
}
```

but unfortunately steampipe rejects it as invalid since we check the list:
```
~/src/steampipe-community-stats $ steampipe query
Welcome to Steampipe v0.8.0
For more information, type .help
> select * from oci_core_subnet
Error: Connection config have invalid regions: sa-vinhedo-1. Edit your connection configuration file and then restart Steampipe
> 
```

Steps from here:
1. Fix the list of regions to add `sa-vinhedo-1`.
2. Allow specific regions to be given in the config without breaking, so that we can workaround it in situations like this where new regions come out before we add them to the list.

**Comment by valdecircarvalho** [comment]
> As a workaround, I tried adding it explicitly to my config (instead of `*`):

My config file is already like yours, not using * but the region name instead.

So, should I expect a fix in a near future right? :) 
Thanks for the amazing support @e-gineer Nathan!

**Comment by valdecircarvalho** [comment]
Hello there guys! So, does it means the issue is fixed?
Thanks!

**Comment by bigdatasourav** [comment]
Hi @valdecircarvalho, The issue is fixed, we have added support for sa-vinhedo-1. It will be release today. let us know in case further observations.
