### ISSUE TITLE
Last updated timestamp unavailable for OCI

### ISSUE THREAD

**Issue by saisankar2020** [turbot/steampipe-plugin-oci#315]
Hi,

We are trying to use steampipe in our organization for pulling OCI data. We are unable to find the last updated timestamp for the below tables. Could you please add this timestamp to below tables so that it would be very helpful for our data analytics. Really appreciate the help in advance. 

Tables:

NETWORK_SECURITY_GROUP_RULES
NETWORK_SECURITY_GROUP
ROUTE_TABLE
ROUTE_TABLE_RULES
SECURITY_LISTS
SECURITY_LISTS_INGRESS_RULES
SECURITY_LISTS_EGRESS_RULES
SUBNET
VCN 

Thanks,
Sai Sankar Tummalapalli

**Comment by cbruno10** [comment]
Hey @saisankar2020 , we've checked again and still don't see the last updated timestamp for the resource types you've mentioned above. If you're still interested in these, I'd suggest raising a support request with the OCI support team and/or the OCI Go SDK team to add these fields. If you have any other questions, please let us know!
