### ISSUE TITLE
oci_cloud_guard_target returns no result

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-oci#319]
**Describe the bug**
`oci_cloud_guard_target` returns no data for` select * oci_cloud_guard_target` query

it's wired that the CLI also returns no data 

```
turbot-macpro-raj:steampipe-plugin-aws raj$ oci cloud-guard target list --compartment-id ocid1.compartment.oc1..aaaaaaaapysrwqktbfsfsdfdsfdsfdsfds
  "data": {
    "items": []
  }
}
```

**Steampipe version (`steampipe -v`)**
Example: v0.9.0

**Plugin version (`steampipe plugin list`)**
Example: v0.3.1

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).
Create the managed list in Cloud Guard and execute ` select * oci_cloud_guard_target`

Area to look for,
It could have been affected to few tables, need further deep investigation

1. Whether previous versions working? Yes, as the new table results show in the respective PR
2. Might have broken from the new SDK version, hence we might have to start checking since 

**Expected behavior**

**Additional context**

**Comment by bigdatasourav** [comment]
https://github.com/turbot/steampipe-plugin-oci/issues/278
