### ISSUE TITLE
Handle errors in filter columns.

### ISSUE THREAD

**Issue by c0d3r-arnab** [turbot/steampipe-plugin-oci#330]
Handle `InvalidParameter` exceptions in quals columns. E.g.
> select * from oci_apigateway_api where display_name = ''
Error: Service error:InvalidParameter. Invalid displayName. http status code: 400. Opc request id: 9e95c584e509c13673ae1277896fce57/672D9B49AB28D540176A871436B347B7/91E0772D3815FEFFCFE478DDCD1DD9C4

> select * from oci_core_dhcp_options where lifecycle_state = 'tes'
Error: Service error:BadErrorResponse. Failed to parse json from response body due to: json: cannot unmarshal number into Go struct field servicefailure.code of type string. With response body {
  "code" : 400,
  "message" : "query param lifecycleState must be one of [Provisioning, Available, Terminating, Terminated]"
}.. http status code: 400. Opc request id: b2f9eae271989354e4e3bf7d7925ab09/B1BA495E12DAF9F9348E8E96DC39288E/19434587C22A068D59672F80A5955997

> select * from oci_identity_group where lifecycle_state = 'test'
Error: Service error:InvalidParameter. lifecycleState is invalid or incorrectly formatted. http status code: 400. Opc request id: 3ff0289a21e9e050e3ff7c89477e7a79/41347AAB984A9A50A426847A1295D76B/340E5482EF51718D9EE8D6D6E7F2AC32

Tables:

- [ ] oci_identity_user
- [ ] oci_identity_group
- [ ] oci_identity_compartment
- [ ] oci_apigateway_api
- [ ] oci_core_dhcp_options

**Comment by rajlearner17** [comment]
Maybe we can handle it if an external user's request is raised with a valid reason. Currently, the errors are coming based on invalid input, which we can have as is.
