### ISSUE TITLE
Add table oci_functions_function

### ISSUE THREAD

**Issue by recursivecodes** [turbot/steampipe-plugin-oci#336]
https://registry.terraform.io/providers/hashicorp/oci/latest/docs/resources/functions_function
https://docs.oracle.com/en-us/iaas/Content/Functions/Concepts/functionsoverview.htm

**Comment by rajlearner17** [comment]
@recursivecodes Appreciate checking out steampipe! 👍  We will look into it based on GO SDK availability.

**Comment by recursivecodes** [comment]
No worries. Let me know if you have SDK issues, I can bring them to the OCI team.
