### ISSUE TITLE
Add table oci_mysql_analytics_cluster

### ISSUE THREAD

**Issue by bigdatasourav** [turbot/steampipe-plugin-oci#374]
**References**
Required for OCI reporting.
https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/mysql_analytics_cluster

**Comment by karanpopat** [comment]
OCI MySQL Analytics cluster is deprecated, and MySQL Heat Wave Cluster has to be used instead. Issue #375 fulfils the requirement for the same. 
**Reference**: https://docs.oracle.com/en-us/iaas/api/#/en/mysql/20190415/AnalyticsCluster/GetAnalyticsCluster
