### ISSUE TITLE
Fix list call for table oci_core_image_custom 

### ISSUE THREAD

**Issue by c0d3r-arnab** [turbot/steampipe-plugin-oci#378]
**Describe the bug**
The list for table oci_core_image_custom is returning empty rows even though data is present.

Custom images can be created in two ways.
1. Importing the image from the bucket (In this case we will have OperatingSystem value as 'Custom' and BaseImageId will be null)
2. Exporting an image from an instance (In this case we will have OperatingSystem value as per the instance OS image and BaseImageId will not be null)
3. We are segregating the custom images based on `BaseImageId` so if we create a custom image by following point number 2 then it is not being reflected in the table.
```
> select * from oci_core_image_custom
+--------------+----+-----------------+--------------+---------------+----------------------+-------------+----------------+------------------+--------------------------+-------------+----------------+---
| display_name | id | lifecycle_state | time_created | base_image_id | create_image_allowed | launch_mode | launch_options | operating_system | operating_system_version | size_in_mbs | agent_features | de
+--------------+----+-----------------+--------------+---------------+----------------------+-------------+----------------+------------------+--------------------------+-------------+----------------+---
+--------------+----+-----------------+--------------+---------------+----------------------+-------------+----------------+------------------+--------------------------+-------------+----------------+---
```

**Steampipe version (`steampipe -v`)**
Example: v0.13.3

**Plugin version (`steampipe plugin list`)**
Example: v0.9.0

**To reproduce**
Run the following command:
```
select * from oci_core_image_custom
```

**Expected behavior**
The list call should return values when present

**Comment by ParthaI** [comment]
The api/CLI doesn't return the response as we expect, A support request has been raised for it.

**Comment by misraved** [comment]
Closing this since it is not on priority.
