### ISSUE TITLE
overcome rate limiting

### ISSUE THREAD

**Issue by judell** [turbot/steampipe-plugin-oci#395]
A user reports being unable to run the OCI Compliance mod, in whole or even in part, due to 429 "too many requests" errors.

> -I tried to run the individual controls, region by region, editing  the oci.spc file. It helped in some cases, but I couldn't run all the controls.
> -I had to edit and run the 2.Networking queries manually. I removed left joins that caused recurring calls to OCI when trying to retrieve both compliant and non-compliant security rules to report, leaving the result with only non-compliant rules, what served my purpose.

He asks:

> Is there any way to parameterize the requests per second or any other approach?

**Comment by rajlearner17** [comment]
@judell Thanks for notifying this; I ran compliance queries without much issue. However, that may exist, as you have indicated. Pls, provide any reference to particular queries to test with. What regions did you query for?

**Comment by DonMichel** [comment]
@rajlearner17 
I run compliance queries without much issue, too, until this tenancy.
The controls that are failing are all of "CIS Benchmark: 2 Networking":
```
 oci_compliance.control.cis_v110_2_1
 oci_compliance.control.cis_v110_2_2
 oci_compliance.control.cis_v110_2_3
 oci_compliance.control.cis_v110_2_4
 oci_compliance.control.cis_v110_2_5
```
I have tried to run on individual regions, once at a time, without success.

I am sure the cause is the high number of RULES in Security lists and Network Security Groups in the Tenancy:
Number of Regions: 2

```
Security lists per region:

Region #1: 35
Region #2: 95

NSG per region:
Region #1: 30
Region #2: 70

Total number of Rules in Security Lists per region:
Region #1: 785
Region #2: 1924

Total number of Rules in NSG per region:
Region #1: 603
Region #2: 2274
```

**Comment by rajlearner17** [comment]
@DonMichel Appreciate this insight, and we will try replicating the same and see what best we can do here to avoid this.

**Comment by DonMichel** [comment]
Hello @ParthaI, thanks for your help and I´ll be glad to contribute.
Unfortunately, I am having an error with "make", maybe go version? I installed "go1.16.13 linux/amd64". Should I try another one?
```
go: google.golang.org/genproto@v0.0.0-20200526211855-cb27e3aa2013 requires
        google.golang.org/protobuf@v1.23.1-0.20200526195155-81db48ad09cc: 
 (...)
 fatal: git fetch-pack: expected shallow list
make: *** [install] Error 1
```

**Comment by DonMichel** [comment]
@ParthaI, the PR solved the problem.
I tested in two tenancies with high number of Security Rules, and now it's working  smoothly!
Thank you!

**Comment by judell** [comment]
Nice going @ParthaI!
