### ISSUE TITLE
Add tables oci_database_autonomous_exadata_infrastructure and oci_database_autonomous_container_database

### ISSUE THREAD

**Issue by javierbm7** [turbot/steampipe-plugin-oci#404]
**References**
Add any related links that will help us understand the resource, including vendor documentation, related GitHub issues, and Go SDK documentation.

I want the exadata autonomous infrastructure to be included because this will allow queries to about autonomous exadata databases normall used by large customers:

tables: autonomous-container-database, autonomous-exadata-infrastructure

https://docs.oracle.com/en-us/iaas/tools/oci-cli/3.8.1/oci_cli_docs/cmdref/db/autonomous-exadata-infrastructure.html

**Comment by rajlearner17** [comment]
@javierbm7 Thanks for using Steampipe!
We will check its feasibility based on the API support and prioritise this. Thank you for your continuous feedback.
