### ISSUE TITLE
Missing fault domains in MySQL DB systems

### ISSUE THREAD

**Issue by hrishikeshkalita** [turbot/steampipe-plugin-oci#421]
**Describe the bug**
We have configured MySQL DB systems for High Availability and hence it is deployed under multi fault domain architecture. But, while we tried running a query to fetch the fault domains, we can see only 1 FD and not the others.
Query:
```
select
  display_name,
  fault_domain
from
  oci_mysql_db_system
where
  lifecycle_state = 'ACTIVE'
```
**Steampipe version (`steampipe -v`)**
steampipe version 0.15.0

**Plugin version (`steampipe plugin list`)**
steampipe plugin oci version 0.14.1

**To reproduce**
Pre-requisite:
1. MySQL DB System on OCI with High Availability Enabled
2. OCI CLI installed and configured with access keys
3. Steampipe installed along with oci plugin

Steps:
1. Run `steampipe query`
2. Run the following query
```
select
  display_name,
  fault_domain
from
  oci_mysql_db_system
where
  lifecycle_state = 'ACTIVE'
```

**Expected behavior**
The query should have given a list of fault domains for multi FD configuration.

**Additional context**

**Comment by bigdatasourav** [comment]
Hey @hrishikeshkalita, apologies to see that you are facing this issue.

The ListDbSystems and GetDbSystem APIs return the selected/preferred fault domain detail. It does not return all the fault domains. Here is a [document](https://docs.oracle.com/en-us/iaas/mysql-database/doc/high-availability1.html#GUID-E7EABBE3-3A17-4EC8-B4DE-E9654E818B5C) that details how AD and FD used to choose for the High Availability DB system.

Regarding the API issue, I have raised an [issue](https://github.com/oracle/oci-go-sdk/issues/371) in OCI GO SDK.
