### ISSUE TITLE
Add table oci_MYSQL_shapes

### ISSUE THREAD

**Issue by AnykeyNL** [turbot/steampipe-plugin-oci#425]
Is it possible to add the MYSQL shapes list as a table?

https://docs.oracle.com/en-us/iaas/tools/python/2.85.0/api/mysql/client/oci.mysql.MysqlaasClient.html#oci.mysql.MysqlaasClient.list_shapes

This will allow you to resolve the actual OCPU and Memory for the running MySQL instances.

**Comment by misraved** [comment]
Welcome to Steampipe @AnykeyNL 👍 . Thank you for raising the feature request 😄.

If anyone would like to attempt to develop this table, the [API](https://github.com/oracle/oci-go-sdk/blob/master/mysql/list_shapes_request_response.go) is an excellent place to start.

Please let us know in case there are questions 👍 .

**Comment by scotti-fletcher** [comment]
I will add this information. Does it make sense to add it as a separate table? Or just extent the mysql_db_system table? Given it's only 2 extra fields it might make more sense to extend the table rather than doing an extra SQL join?

**Comment by misraved** [comment]
@scotti-fletcher that's a good point. I don't think e need a new table for this, since it is just an extension of `MySQL` database.

To add to it, since the API doesn't have pagination, I think it is better to add it in the form of new columns than tables.

**Comment by scotti-fletcher** [comment]
@misraved I've created a PR for these extra fields

https://github.com/turbot/steampipe-plugin-oci/pull/438/commits

**Comment by misraved** [comment]
Resolved in https://github.com/turbot/steampipe-plugin-oci/pull/483
