### ISSUE TITLE
Steampipe integration with oracle cloud shell

### ISSUE THREAD

**Issue by opengitwork** [turbot/steampipe-plugin-oci#429]
Steampipe is not able to authenticate within oracle cloud shell . Have to configure other supported authentication method manually to make it work.

**Comment by misraved** [comment]
Welcome to Steampipe @opengitwork 👍. Thanks for raising this feature request.

Have you tried to connect to Steampipe using this form of configuration - https://github.com/turbot/steampipe-plugin-oci/blob/main/docs/index.md#instance-principal-based-authentication?

I am not super familiar with the Oracle cloud shell, but could you please share the error that you are getting when trying to connect to steampipe using oracle cloud shell?

**Comment by opengitwork** [comment]
yes i tried other connection settings and it works . But the purpose of cloudshell is to avoid doing those manual settings. The error i got was related to authentication as there will  be no config in default location ~/.oci/config in cloudshell . Could you please check whether identity provider used is latest in steampipe to support cloudshell.

Error: can not create client, bad configuration: did not find a proper configuration for user (SQLSTATE HV000)
