### ISSUE TITLE
Select display_name against oci_core_instance returns <null>

### ISSUE THREAD

**Issue by martinberger-ch** [turbot/steampipe-plugin-oci#430]
**Describe the bug**
A SELECT query against oci_core_instance with column DISPLAY_NAME returns <null> instead of OCI Display Name.

**Steampipe version (`steampipe -v`)**
steampipe version 0.17.4

**Plugin version (`steampipe plugin list`)**
+--------------------------------------------+---------+-------------+
| Installed Plugin                           | Version | Connections |
+--------------------------------------------+---------+-------------+
| hub.steampipe.io/plugins/turbot/oci@latest | 0.17.2  | oci         |
+--------------------------------------------+---------+-------------+

**To reproduce**
[steampipe@ci-steampipe-2022 .oci]$ docker exec -it steampipe steampipe plugin update oci

turbot/oci           [====================================================================] Latest already installed

[steampipe@ci-steampipe-2022 .oci]$ docker exec -it steampipe steampipe query "select display_name,shape,region from oci_core_instance where lifecycle_state='RUNNING';"
+--------------+---------------------+-------------+
| display_name | shape               | region      |
+--------------+---------------------+-------------+
| <null>       | VM.Standard.E4.Flex | eu-zurich-1 |
| <null>       | VM.Standard.E4.Flex | eu-zurich-1 |
| <null>       | VM.Standard.E4.Flex | eu-zurich-1 |
| <null>       | VM.Standard.E4.Flex | eu-zurich-1 |
| <null>       | VM.Standard2.4      | eu-zurich-1 |
| <null>       | VM.Standard.E4.Flex | eu-zurich-1 |
| <null>       | VM.Standard.E4.Flex | eu-zurich-1 |
+--------------+---------------------+-------------+

**Expected behavior**
Instead of <null>, the display name is shown.

**Additional context**

**Comment by misraved** [comment]
Hello @martinberger-ch, thanks for raising the bug.

I tried to replicate the issue but without much success. 

I was successfully able to query the resource - 
```
steampipe query "select display_name,shape,region from oci_core_instance where lifecycle_state='RUNNING';"
+------------------------+---------------------+-------------+
| display_name           | shape               | region      |
+------------------------+---------------------+-------------+
| instance-121212-11111 | VM.Standard.E4.Flex | ap-mumbai-1 |
+------------------------+---------------------+-------------+
```

I think in your output as well, I see a blank column name, however it seems like it has compressed to merge with the `shape` column.

**Comment by martinberger-ch** [comment]
The permissions are the problem -but it's solved:

allow group oci_group_readonly to inspect all-resources on tenancy
allow group oci_group_readonly to manage all-resources in tenancy where request.operation='GetConfiguration'

Changing verb from INSPECT to READ has solved it. Sorry to disturb you.

**Comment by martinberger-ch** [comment]
The permissions are the problem -but it's solved:

allow group oci_group_readonly to inspect all-resources on tenancy
allow group oci_group_readonly to manage all-resources in tenancy where request.operation='GetConfiguration'

Changing verb from INSPECT to READ has solved it. Sorry to disturb you.

**Comment by misraved** [comment]
Great to see that you are unblocked for now @martinberger-ch 👍.

Thanks for bringing the permission issue to light 😃 .

I am closing this issue for now, please let us know if you run into more issues 👍.
