### ISSUE TITLE
Encryption with CMK not getting reflected in table data of oci_database_autonomous_database

### ISSUE THREAD

**Issue by madhushreeray30** [turbot/steampipe-plugin-oci#434]
Values for `key_store_id` as well as `key_store_wallet_name` is coming null when encrypted with CMK 
![Screenshot 2022-12-26 at 2 08 34 PM](https://user-images.githubusercontent.com/65847563/209526215-b1b9aa0f-271e-428d-8399-33594795b07e.png)

**Comment by ParthaI** [comment]
- The properties KmsKeyId, VaultId, KmsKeyLifecycleDetails and KmsKeyVersionId should be added to this table.
- The API response of [ListAutonomousDatabases](https://pkg.go.dev/github.com/oracle/oci-go-sdk/v44@v44.0.0/database#DatabaseClient.ListAutonomousDatabases) contains the above mentioned attributes.
- However we are getting null value for these attributes. Raised a support request with [OCI Go SDK](https://github.com/oracle/oci-go-sdk/issues/397) end.
