### ISSUE TITLE
No join possible between oci_file_storage_mount_target and oci_file_storage_file_system

### ISSUE THREAD

**Issue by madhushreeray30** [turbot/steampipe-plugin-oci#436]
table `oci_file_storage_file_system` should contain detail of `mount_target_id` or table `oci_file_storage_mount_target` should contain detail of `file_system_id`  to ensure join between the two tables.

**Comment by rajlearner17** [comment]
This is addressed by https://github.com/turbot/steampipe-plugin-oci/pull/450
