### ISSUE TITLE
Add missing oci_api_gateway tables

### ISSUE THREAD

**Issue by scotti-fletcher** [turbot/steampipe-plugin-oci#440]
Tables that are missing:

oci_api_gateway_certificate
oci_api_gateway_deployment
oci_api_gateway_gateway
oci_api_gateway_sdk
oci_api_gateway_subscriber
oci_api_gateway_usage_plan.

**Comment by scotti-fletcher** [comment]
I've created the tables but have raised a ticket with Oracle Go SDK team as the SDK is missing the user-agent in the HTTP request headers causing the requests to fail. 

The requests affected are:

- ListDeployments
- ListGateways
- ListSubscribers
- ListUsagePlans

ListCertificates works as expected.

**Comment by bigdatasourav** [comment]
Hey @scotti-fletcher, did the above issue gets resolved? Can you now proceed with the tables? Please don't hesitate to let us know if there is anything we can do to help you further.

**Comment by bigdatasourav** [comment]
Hey @scotti-fletcher, We are closing this issue because we have not heard from you. Please feel free to reopen the issue if you want to share or discuss anything.
