### ISSUE TITLE
Update oci_apigateway_api table name to oci_api_gateway_api to follow naming convention

### ISSUE THREAD

**Issue by scotti-fletcher** [turbot/steampipe-plugin-oci#441]
The table name oci_apigateway_api does not follow standard naming conventions

**Steampipe version (`steampipe -v`)**
steampipe version 0.17.2

**Plugin version (`steampipe plugin list`)**
Latest - custom version

**To reproduce**
select * from oci_apigateway_api

**Expected behavior**
select * from oci_api_gateway_api

**Additional context**
The name should be updated to follow correct naming conventions.

**Comment by misraved** [comment]
Thank you @scotti-fletcher for raising this issue 👍. Typically we tend to keep the service name as a single word(no underscores) while creating table names. The structure looks like this - `oci` _ `servicename` _ `resourcename`.

So in this case, I believe `apigateway` should be used instead of `api_gateway`.

@cbruno10 thoughts?

**Comment by scotti-fletcher** [comment]
Thanks for clarifying Ved.

So just to clarify, certificatesmanagement should also be like that? If
that’s the case I’ll update the other tables I’ve created too.

**Comment by cbruno10** [comment]
In this case, I think the current table name, `oci_apigateway_api` is correct. For plugin tables names, if there's a corresponding Terraform plugin, we often use that (but can deviate if necessary, like `aws_instance` is better as `aws_ec2_instance`).

For this table, the Terraform resource is named [apigateway_api](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/apigateway_api), so our table name would be `oci_apigateway_api`.

For more info on how we name tables (and columns), please see https://steampipe.io/docs/develop/standards#naming.

**Comment by scotti-fletcher** [comment]
Thanks @cbruno10 I'll ket that in mind for future!
