### ISSUE TITLE
Update table oci_containerengine_cluster to following naming convention

### ISSUE THREAD

**Issue by scotti-fletcher** [turbot/steampipe-plugin-oci#447]
The table name "oci_containerengine_cluster" should follow naming conventions and be "oci_container_engine_cluster"

**Comment by cbruno10** [comment]
As mentioned in https://github.com/turbot/steampipe-plugin-oci/issues/441#issuecomment-1371326955, I think the current table name is correct, as the Terraform resource is named [containerengine_cluster](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/containerengine_cluster).

As a note, sometimes within the TF provider, the resource names are a bit inconsistent. For instance, for some services, they substitute spaces with `_`, but for others, they just remove spaces and keep the service as one word.

In any case, I believe  if the plugin table names are consistent with Terraform (even if the resource names are a bit inconsistent), this gives us the easiest path forward to determining table names.

**Comment by scotti-fletcher** [comment]
Thanks @cbruno10. I'll keep that in mind moving forward.
