### ISSUE TITLE
Add column to show the number of child tables of a nosql table

### ISSUE THREAD

**Issue by madhushreeray30** [turbot/steampipe-plugin-oci#451]
![5CA8172F-99A4-4D83-A3D9-5CBECE2B1F48_4_5005_c](https://user-images.githubusercontent.com/65847563/210724814-adee0924-2712-46d1-925a-f627a807b077.jpeg)

**Comment by ParthaI** [comment]
We are using the [ListTables](https://pkg.go.dev/github.com/oracle/oci-go-sdk@v24.3.0+incompatible/nosql#NosqlClient.ListTables)/ [GetTable](https://pkg.go.dev/github.com/oracle/oci-go-sdk@v24.3.0+incompatible/nosql#NosqlClient.GetTable) APIs to get the details of the NoSQL tables. Also there is no separate API call for getting the number of child tables available for a table.

I have raised a support request with Go SDK. Ref: https://github.com/oracle/oci-go-sdk/issues/422

**Comment by ParthaI** [comment]
As per the [Go SDK issue discussion](https://github.com/oracle/oci-go-sdk/issues/422), we can add a separate table named `oci_nosql_child_table`. The parent will be the `oci_nosql_table`.

We will continue working on it as per priority.

**Comment by ParthaI** [comment]
Thank you, @rajlearner17. My intention was to submit a pull request by directly including the example queries within the documentation. I appreciate your assistance! 👍

**Comment by ParthaI** [comment]
Addressed in: https://github.com/turbot/steampipe-plugin-oci/pull/535
