### ISSUE TITLE
Getting null value for column `exports` in table `oci_file_storage_file_system` specifically for get call

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-oci#465]
**Describe the bug**
Getting null value for column `exports` in table `oci_file_storage_file_system`, This happens with get call, with list call we are getting the data.

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by bigdatasourav** [comment]
This should be a separate table - https://github.com/turbot/steampipe-plugin-oci/issues/473
