### ISSUE TITLE
Add table oci_queue_queue

### ISSUE THREAD

**Issue by lucasjellema** [turbot/steampipe-plugin-oci#480]
To query Queues on OCI through Steanpipe

**References**
[Terraform resource definition of Queue resource in Queue service
](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/queue_queue)
[OCI Documentation on Queue](https://docs.oracle.com/en-us/iaas/Content/queue/home.htm)
[OCI Go SDK documentation on the Queue resource](https://pkg.go.dev/github.com/oracle/oci-go-sdk/v65@v65.28.0/queue)

**Comment by misraved** [comment]
Welcome to Steampipe @lucasjellema 😃 and thanks for raising this issue 👍.

If anyone would like to attempt to develop this table, the API links provided by @lucasjellema are an excellent place to start.

Please let us know in case there are questions 👍 .

**Comment by lucasjellema** [comment]
Actually, I have already done the implementation and created a Pull Request - https://github.com/turbot/steampipe-plugin-oci/pull/481 - with the code that I believe fixes this issue. I forgot to include the incident link in the pull request though

**Comment by lucasjellema** [comment]
The pull request that addresses this issue has been merged to main. This issue can be closed.
