### ISSUE TITLE
Add table oci_container_instances_container_instance

### ISSUE THREAD

**Issue by lucasjellema** [turbot/steampipe-plugin-oci#491]
**References**
Recently introduced service OCI Container Instances

OCI Docs: https://docs.oracle.com/en-us/iaas/Content/container-instances/home.htm
Terraform Resource: https://registry.terraform.io/providers/oracle/oci/latest/docs/data-sources/container_instances_container_instances
Go SDK https://pkg.go.dev/github.com/oracle/oci-go-sdk/v65@v65.28.0/containerinstances

**Comment by lucasjellema** [comment]
I am working to provide the solution for this issue on this branch: https://github.com/lucasjellema/steampipe-plugin-oci/tree/add-table-oci_container_instances_container_instance . Most relevant columns are already supported.

**Comment by lucasjellema** [comment]
Creating the test has not been successful because of an error in OCI APIs with Terraforming oci_container_instances_container_instance. I have created a support request to have the error looked into.

**Comment by bigdatasourav** [comment]
Hey @lucasjellema, did the above issue gets resolved? Can you now proceed with the table? If the table works fine, you can raise a PR(Table +Doc) without the Terraform test. We can work on the terraform test later. Please don't hesitate to let us know if there is anything we can do to help you further.
