### ISSUE TITLE
No means to deal with an api key that has a passphrase set

### ISSUE THREAD

**Issue by tpresence** [turbot/steampipe-plugin-oci#499]
If your api private key has a passphrase assigned to it, there is no means to input that phrase so the key can be used.
Error is : "Error: can not create client, bad configuration: did not find a proper configuration for private key (SQLSTATE HV000)"

When attempting to use the tool using an API key that has a passphrase assigned, the tool could ask the user for the passphrase.

**Comment by cbruno10** [comment]
@tpresence No problem, thanks for the info!

Can you please share your `~/.steampipe/config/oci.spc` and your OCI config file (both with sensitive info removed)? Also, are you able to authenticate with the OCI CLI using the same OCI config file?

**Comment by tpresence** [comment]
I have no trouble working with the oci cli using the config that is in place.  When I make an oci request, it asks me for the passphrase of the key and then processes the request.
Example:
$ oci os ns get
Private key passphrase: _<type in passphrase>_
{
  "data": "namespace"
}
oci.spc:
connection "oci" {
  plugin = "oci"
  config_file_profile = "DEFAULT"
  config_file_path = "~/.oci/config"

  # List of regions
  regions = ["us-phoenix-1"]
}
config:
user=<user ocid>
fingerprint=<user api key fingerprint>
tenancy=<tenancy ocid>
region=us-phoenix-1
compartment-id=<compartment ocid>
key_file=<path to keyfile>

**Comment by cbruno10** [comment]
@tpresence Can you please try setting the `private_key_password` config arg in your `~/.steampipe/config/oci.spc` and then try the queries again? We don't support the `OCI_CLI_PASSPHRASE`, but we should, as a more secure way to set the passphrase.

By the way, does setting the `OCI_CLI_PASSPHRASE` work for you in the CLI?

An alternate way is to set `pass_phrase` in your OCI config file as per https://docs.oracle.com/en-us/iaas/Content/API/Concepts/sdkconfig.htm#File_Entries, but as noted there, that entry is deprecated and should not be used.

**Comment by cbruno10** [comment]
@tpresence I've also created https://github.com/turbot/steampipe-plugin-oci/issues/500 and https://github.com/turbot/steampipe-plugin-oci/issues/501 based on difficulties I had finding this info in our code base.

**Comment by tpresence** [comment]
yeah, putting the phrase in the oci config file works for the oci cli and with steampipe, but its a terrible solution.  I get that having it ask interactively won't work with automation, and a vault should be used for this.  I couldn't get the private_key_password in the oci.spc file to work with or without  private_key_path set.

**Comment by cbruno10** [comment]
@tpresence We're tracking the work in https://github.com/turbot/steampipe-plugin-oci/issues/500 and https://github.com/turbot/steampipe-plugin-oci/issues/501, so I'm closing this issue for now, but if you have any additional questions/observations, please feel free to share them in one of the linked issues that matches the context best. Thanks!
