### ISSUE TITLE
Unable to Retrieve Object Storage Consumption Numbers

### ISSUE THREAD

**Issue by simonneto** [turbot/steampipe-plugin-oci#530]
**Describe the bug**
I am trying to gather how much object storage is being used in a tenancy. But the numbers we are getting are not matching with the cost report or the limits.

**Steampipe version (`steampipe -v`)**
v0.20.9

**Plugin version (`steampipe plugin list`)**
0.28.0

**To reproduce**
Tried running this query:
`select
  name,
  approximate_size
from
  oci_objectstorage_bucket;`

but the approximate size is coming back null

Tried to sum the size by object by running this query:
`select archival_state,sum((size/1024/1024/1024))
from
  oci_objectstorage_object
group by archival_state;`

but its only returning around 11TB when we now we are using over 200TB
+----------------+-------+
| archival_state     | sum     |
+----------------+-------+
|                              | 11440 |
| Archived              | 0          |
+----------------+-------+

**Expected behavior**
Return a number that is consistent with the Cost Analysis report or the Usage and Limits page

**Additional context**
Just for reference, I am writing similar queries to collect block and boot volume space and that is consistent with the reports.

**Comment by rajlearner17** [comment]
@simonneto Great to see you diving into using the plugin and helping us with this feedback. Thanks

This one seems buggy, as I see `select name, approximate_size from oci_objectstorage_bucket;` returns `null` for me as well. I don't know if something changed the underlying API or if it was like this. 

We need more time to investigate this one and see what we can do to fix this. Expect us to respond!

**Comment by bigdatasourav** [comment]
Hey @simonneto, we have successfully replicated the problem mentioned above.

There appears to be an issue with the GetBucket API used in the `oci_objectstorage_bucket` table, as it should return the approximate_size. Similarly, the ListObjects API used in the `oci_objectstorage_object` table should provide the actual object size. We believe this to be an API-related problem. We have reported the [issue](https://github.com/oracle/oci-go-sdk/issues/443) to the OCI SDK team, and we encourage you to share any updates or feedback you may have on this matter. If you have any findings or additional feedback, please don't hesitate to let us know.

**Comment by cbruno10** [comment]
Closing this issue as we're blocked until https://github.com/oracle/oci-go-sdk/issues/443 is resolved or there's a workaround we can use. Once resolved, we can re-open this issue to test/verify the table is returning the correct information.
