### ISSUE TITLE
Add last_successful_login_time column to oci_identity_user table 

### ISSUE THREAD

**Issue by fatih-keles** [turbot/steampipe-plugin-oci#546]
**References**
Can you add last_successful_login_time column to the oci_identity_user table? 
![last-successful-login-time](https://github.com/turbot/steampipe-plugin-oci/assets/34371716/031f5d0b-78e8-4fae-8351-9e0d5bacbd70)

**Comment by fatih-keles** [comment]
I've added on my local, it is working but couldn't push the branch.

**Comment by madhushreeray30** [comment]
@fatih-keles Welcome to Steampipe and thanks for raising the issue! It has been addressed in #547
