### ISSUE TITLE
Add table oci_database_exadata_infrastructure

### ISSUE THREAD

**Issue by hslange** [turbot/steampipe-plugin-oci#570]
**References**
[GetCloudExadataInfrastructure](https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/CloudExadataInfrastructure/GetCloudExadataInfrastructure)
to obtain the information about an Exadata Infrastructure deployed in OCI
This call will return a single [CloudExadataInfrastructure](https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/CloudExadataInfrastructure/) resource with all the details about the infrastructure.

**Comment by hslange** [comment]
Use [ListCloudExadataInfrastructures ](https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/CloudExadataInfrastructure/ListCloudExadataInfrastructures) to get a list of the cloud Exadata infrastructure resources in the specified compartment. Applies to Exadata Cloud Service instances and Autonomous Database on dedicated Exadata infrastructure only

**Comment by ParthaI** [comment]
Hello @hslange, thank you for your patience. I've submitted a [draft PR](https://github.com/turbot/steampipe-plugin-oci/pull/582) that introduces a new table, `oci_database_exadata_infrastructure`. I would greatly appreciate it if you could take a look at it in the PR branch (`issue-570`) and provide us with your valuable feedback.

Steps to checking out the code changes:

- git clone https://github.com/turbot/steampipe-plugin-oci.git
- cd steampipe-plugin-oci
- git checkout `issue-570`
- Run the command `make`
- Run the query

Thank You!

**Comment by hslange** [comment]
Hi @ParthaI ,
Thanls for the implementation.
I had a brief look at the code changes.
Initially it looked OK to me, but when I treid to test it agains my environment (with 12 exadata's) non were returned by the query.
Having a closer look I found the " issue".
In OCI, there are 2 forms of Exadata:
- Exadata Cloud Service (ExaCS)
- Exadata Cloud at Customer (ExaCC)
Both have different API's:
- EXACS: https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/CloudExadataInfrastructure/
- EXACC: https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/ExadataInfrastructure/

I think what you have implemented is the EXACC variant (which was als missing), but since I don't have access to it, I can't do any further testing.
Please make sure this becomes clear from the table and columns descriptions, because this is quite confusing.
Please continue but I would like to see the EXACS variant as well. It should not be very difficult, the API looks similar but has less fields. But it needs a different 'table' in steampipe. 
Can I suggest: oci_database_cloud_exadata_infrastructure ?
Hope this is useful feedback.
Kind regards,
Herman

**Comment by ParthaI** [comment]
Thanks, @hslange, for your quick response.

Ahh, I got it. OCI treats them as two different types of resources.
- [oci_database_exadata_infrastructure](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/database_exadata_infrastructure)
- [oci_database_cloud_exadata_infrastructure](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/database_cloud_exadata_infrastructure)

It would be a separate table named `oci_database_cloud_exadata_infrastructure`. I have raised an issue to add this support in Steampipe. I will take a look at it and add it in.  Issue ref: https://github.com/turbot/steampipe-plugin-oci/issues/584

Thank you!

**Comment by ParthaI** [comment]
Hello @hslange, I'm sorry for the extended period of silence regarding this matter.

I have raised another [draft PR](https://github.com/turbot/steampipe-plugin-oci/pull/598) by adding a new table named `oci_database_cloud_exadata_infrastructure`. It would be immensely helpful if you could test the changes in the PR branch (`issue-584`) and share your invaluable feedback with us.

Thanks!

**Comment by bigdatasourav** [comment]
We are tracking the `oci_database_cloud_exadata_infrastructure` table issue [here](https://github.com/turbot/steampipe-plugin-oci/issues/584).
