### ISSUE TITLE
Add table oci_database_cloud_vm_cluster

### ISSUE THREAD

**Issue by hslange** [turbot/steampipe-plugin-oci#571]
**References**
This table should provide detailed information about an OCI Exadata Cloud VM Cluster.
Use this API to get the require data: [GetCloudVmCluster](https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/CloudVmCluster/GetCloudVmCluster)
This call will return a single [CloudVmCluster](https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/CloudVmCluster/) resource.

TF reference: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/database_cloud_vm_cluster

**Comment by ParthaI** [comment]
Hello @hslange, I appreciate your patience. I've submitted a [draft pull request (PR)](https://github.com/turbot/steampipe-plugin-oci/pull/583) that introduces a new table called `oci_database_cloud_vm_cluster`. Your feedback on this PR would be highly valuable.

To review the code changes, please follow these steps:

1. Clone the repository: `git clone https://github.com/turbot/steampipe-plugin-oci.git`
2. Navigate to the repository: `cd steampipe-plugin-oci`
3. Switch to the PR branch named `issue-571` using: `git checkout issue-571`
4. Build the code with: `make`
5. Execute the query for review.

Thank you for your assistance in reviewing this contribution.

**Comment by hslange** [comment]
Hi @ParthaI ,
Thanks for the implementation.
This table indeed shows the details of an Exadata Cloud VM cluster.
tested it and most if it works well.
However, some columns return "null" values in the query, where I would expect an actual value.
The following columns returned 'null' in my query (select * from oci_database_cloud_vm_cluster):

- id  - should be there, because a VM cluster needs an OCID
- subnet_id - should also be present
- cpu_core_count - should be there
- cloud_exadata_infrastructure_id - should be there, a VM needs to be on a cluster
- backup_subnet_id
- last_update_history_entry_id
- lifecycle_details
- scan_dns_record_id

Please let me know if you need additional info.
Kind regards,
Herman

**Comment by ParthaI** [comment]
@hslange, Thanks for giving it a try. I appreciate your feedback.

It is my wrong. I needed clarification while implementing the resource types. We have two types of VM clusters for OCI's database service.
1. [oci_database_vm_cluster](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/database_vm_cluster) (Exadata VM Cluster)
2. [oci_database_cloud_vm_cluster](https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/database_cloud_vm_cluster) (Exadata  Cloud VM Cluster)

As per the APIs suggested in the issue descriptions we have added the table `oci_database_cloud_vm_cluster`. I will raise a separate PR to support the table `oci_database_vm_cluster` in Steampipe.

BTW, we should not get any null value, I believe.

Could you please provide the `JSON` output of the `select * from oci_database_cloud_vm_cluster` query, _omitting any sensitive data_? I'm interested in assessing the number of columns that return null values.
  - `steampipe query`
  - `.output json`
  - `select * from oci_database_cloud_vm_cluster`

Also, I've implemented several updates in the `issue-571` branch. Could you sync these changes to your local environment and test them? I'd appreciate feedback on whether any columns are returning null values after these modifications.
- cd steampipe-plugin-oci
- git checkout `issue-571 `
- git pull origin `issue-571`
- Run the command `make`
- Run the query

Thank you!

**Comment by hslange** [comment]
Hi @ParthaI ,
Thanks for your quick fix.
Things lok a lot better now, most of the NULL columns are now filled properly.
I will need some time to extract that json and remove sensitive data. Probable tomorrow I will add the cleaned output to this topic.
But what I've seen so far looks a lot better :)
Kind regards,
Herman

**Comment by ParthaI** [comment]
Thank you for your valuable assistance in testing the recent code changes. 🙂

I've submitted a [Pull Request](https://github.com/turbot/steampipe-plugin-oci/pull/586) to add the `oci_database_vm_cluster` table to Steampipe. It would be wonderful if you could review and test it on the `issue-585` branch.

Should you require any further support, please feel free to reach out.

Thanks!

**Comment by hslange** [comment]
Hi @ParthaI,
I collected and the output of the query and remove sensitive data.
See the attachement for the result.
The result has 5 different VM clusters, so you see a littel difference in the output.
At the end, I added the json output from the OCI CLI command for the last Exadata VM Cluster.

What I observed quickly:
1. The " data-collection-options" section is named differently in the steampipe output (datacollectionoptions instead of data_collection_options)
2. The field ssl_public_keys is "null" in steampipe output, this is is correct, you should not show the public key.
3. The Tags in the steampipe output are combined into 1 tags section, not making a distinction between the different Tag namespaces (we use 2 different tag namespaces, the default "Oracle tags"  and our own Tag namespace (in some occasions we have additional Tag namespaces. We don't use freeform tags, but I don't see them in the steampipe output.

As you can see, some of the fields are sometimes NULL in OCI and also shown as Null in steampipe (which is correct)

[vm.txt](https://github.com/turbot/steampipe-plugin-oci/files/13786025/vm.txt)

Kind regards,
Herman

**Comment by ParthaI** [comment]
Hello @hslange,
I'd like to pause and sincerely express my gratitude for the time and effort you dedicated to testing the pull requests.

> The " data-collection-options" section is named differently in the steampipe output (datacollectionoptions instead of data_collection_options)

I have pushed the changes by renaming the column to `data_collection_options`

> The Tags in the steampipe output are combined into 1 tags section, not making a distinction between the different Tag namespaces (we use 2 different tag namespaces, the default "Oracle tags" and our own Tag namespace (in some occasions we have additional Tag namespaces. We don't use freeform tags, but I don't see them in the steampipe output.

I have added back the missing tag columns(`freeform_tags` and `defined_tags`) for the tables.

I will take a final look at the PRs and move forward to get the PRs in.

Best regards,
Partha
