### ISSUE TITLE
Outer join between a postgres materialized view and oci FDW foreign tables exhibits inconsistent results depending upon column selection 

### ISSUE THREAD

**Issue by chrisfw** [turbot/steampipe-plugin-oci#588]
Performing an outer join between an oci foreign table and a postgres materialized view when testing for null on the join column results in inconsistent behavior. 

**Steampipe version (`steampipe -v`)**
v0.21.2

**Plugin version (`steampipe plugin list`)**
hub.steampipe.io/plugins/turbot/oci@latest       | 0.33.0  | oci         |
hub.steampipe.io/plugins/turbot/steampipe@latest | 0.10.0  | steampipe

**To reproduce**

I have a materialized view definition as follows:
```
CREATE MATERIALIZED VIEW IF NOT EXISTS oci.eastern_cust_cross_region_backup_mv as
select oic.name as customer,ocbv.display_name, ocbvb.id, ocbvb.boot_volume_id as volume_id,ocbv.size_in_gbs,ocbv.vpus_per_gb,ocbv.region as customer_primary_region, ocbvb.region as customer_backup_region, ocbvb.time_created, ocbv.volume_backup_policy_id,'boot' as volume_type
FROM oci.oci_core_boot_volume_backup ocbvb
inner join oci.oci_core_boot_volume ocbv
on ocbv.id = ocbvb.boot_volume_id
inner join oci.oci_identity_compartment oic 
on ocbv.compartment_id = oic.id
where oic.name in ('redacted','redacted')
and ocbvb.region = 'us-phoenix-1'
and ocbv.volume_backup_policy_id in ('ocid1.volumebackuppolicy.oc1.redacted','ocid1.volumebackuppolicy.oc1.iad.redacted')
union
select oic2.name, ocv.display_name, ocvb.id, ocvb.volume_id, ocv.size_in_gbs,ocv.vpus_per_gb, ocv.region as customer_primary_region, ocvb.region as customer_backup_region, ocvb.time_created, ocv.volume_backup_policy_id,'block' as volume_type
FROM oci.oci_core_volume_backup ocvb
inner join oci.oci_core_volume ocv
on ocv.id = ocvb.volume_id
inner join oci.oci_identity_compartment oic2 
on ocv.compartment_id = oic2.id
where oic2.name in ('redacted','redacted')
and ocvb.region = 'us-phoenix-1'
and ocv.volume_backup_policy_id in ('ocid1.volumebackuppolicy.oc1.iad.redacted','ocid1.volumebackuppolicy.oc1.iad.redacted')
order by customer,volume_type,time_created DESC;
```

I do an outer join to the oci boot and block volume foreign tables in an attempt to find any volumes that don't have a corresponding backup in the 'backup' OCI region.  The query below returns no results as is (which is incorrect), but if I remove the oic.name and ocbv.display_name columns leaving only the id key column (odbv.id) and my synthetic volume_type column, then I get the results I am expecting.  As a workaround, I have been doing a `create table oci.oci_core_volume_localcopy as 
select * from oci.oci_core_volume` and `create table oci.oci_core_boot_volume_localcopy as 
select * from oci.oci_core_boot_volume` and then performing the outer join between the materialized view and the local copies of the oci volume tables I created - those queries return the results as I expect them.

```
select oic."name",ocbv.display_name,ocbv.id,'boot' as volume_type from oci.oci_core_boot_volume_localcopy ocbv
left outer join oci.eastern_cust_cross_region_backup_mv eastcustbu
on ocbv.id = eastcustbu.volume_id
inner join oci.oci_identity_compartment oic 
on ocbv.compartment_id = oic.id
where 1 = 1
and oic.name = 'redacted'
and eastcustbu.volume_id is null
union
select oic2.name,ocv.display_name,ocv.id, 'block' as volume_type from oci.oci_core_volume_localcopy ocv
left outer join oci.eastern_cust_cross_region_backup_mv eastcustbu
on ocv.id = eastcustbu.volume_id
inner join oci.oci_identity_compartment oic2 
on ocv.compartment_id = oic2.id
where 1 = 1
and oic2.name = 'redacted'
and eastcustbu.volume_id is null
order by volume_type,display_name;
```

**Expected behavior**
The outer join behavior should be consistent and not be different depending upon additional columns from the same table that are included in the select.

Any assistance in resolving this issue would be greatly appreciated.

Regards,
Chris Whelan

**Comment by IbereJr** [comment]
I´m getting the same behave on a query joining oci_core_instance with oci_core_image:

select
   t.display_name,
   t.source_details ->> 'imageId' as source_details,
   i.operating_system as os_kind,
   i.operating_system_version as os_version
from
   oci_core_instance as t
   left join oci_core_image as i on (i.id = t.source_details ->> 'imageId')

Several results in this query, has no matches in image table (left side), but if I do a simple select with only image table, filtering image id not found, this query returns the records

Any suggestion ?

**Comment by bigdatasourav** [comment]
@IbereJr, here is a [reference](https://github.com/turbot/steampipe-plugin-oci/issues/528) for the issue you are facing.

**Comment by bigdatasourav** [comment]
Hey @chrisfw, Could you please try the below query and check if this helps -

```
select
  sub_customer.name,
  sub_volume.display_name,
  sub_volume.id,
  sub_volume.volume_type
from (
  select
    oic.id as compartment_id,
    oic.name,
    ocbv.id,
    ocbv.display_name,
    'boot' as volume_type
  from
    oci.oci_core_boot_volume ocbv
  inner join
    oci.oci_identity_compartment oic on ocbv.compartment_id = oic.id
  where
    oic.name = 'redacted'
  
  union all
  
  select
    oic2.id as compartment_id,
    oic2.name,
    ocv.id,
    ocv.display_name,
    'block' as volume_type
  from
    oci.oci_core_volume ocv
  inner join
    oci.oci_identity_compartment oic2 on ocv.compartment_id = oic2.id
  where
    oic2.name = 'redacted'
) as sub_volume
left join
  oci.eastern_cust_cross_region_backup_mv eastcustbu on sub_volume.id = eastcustbu.volume_id
where
  eastcustbu.volume_id is null
order by
  sub_volume.volume_type,
  sub_volume.display_name;
``

**Comment by chrisfw** [comment]
Hi @bigdatasourav ,

I tried it and unfortunately, the query does not run successfully as it appears to be missing a clause.  I get the error below when I attempt to execute it.:
```
SQL Error [42P01]: ERROR: missing FROM-clause entry for table "sub_customer"
  Position: 11
Error position: line: 5 pos: 10
```

Regards,
Chris

**Comment by bigdatasourav** [comment]
Sorry, I missed that. Here is the updated query - 
```
select
  sub_volume.name,
  sub_volume.display_name,
  sub_volume.id,
  sub_volume.volume_type
from (
  select
    oic.id as compartment_id,
    oic.name,
    ocbv.id,
    ocbv.display_name,
    'boot' as volume_type
  from
    oci.oci_core_boot_volume ocbv
  inner join
    oci.oci_identity_compartment oic on ocbv.compartment_id = oic.id
  where
    oic.name = 'redacted'
  
  union all
  
  select
    oic2.id as compartment_id,
    oic2.name,
    ocv.id,
    ocv.display_name,
    'block' as volume_type
  from
    oci.oci_core_volume ocv
  inner join
    oci.oci_identity_compartment oic2 on ocv.compartment_id = oic2.id
  where
    oic2.name = 'redacted'
) as sub_volume
left join
  oci.eastern_cust_cross_region_backup_mv eastcustbu on sub_volume.id = eastcustbu.volume_id
where
  eastcustbu.volume_id is null
order by
  sub_volume.volume_type,
  sub_volume.display_name;
```

**Comment by bigdatasourav** [comment]
Hey @chrisfw, we're closing this issue as we haven't heard back from you, please feel free to reopen if you want to share anything. Thanks!

**Comment by chrisfw** [comment]
Hi @bigdatasourav , apologies for the delay.  I tested the query you provided and it seems to work ok.  I wouldn't think though that this issue should be closed regardless since this alternative query is a workaround and my original query is valid and should return the same/correct results. 

Thanks,
Chris
