### ISSUE TITLE
Missing schema name for oci_database_db

### ISSUE THREAD

**Issue by hslange** [turbot/steampipe-plugin-oci#589]
**Describe the bug**
The table oci_databae_db is missing a schema/column: database_management_config.
This column provides information if OCI Database Management is enabled or not for this database and if so, what the state is.

**Steampipe version (`steampipe -v`)**
 v0.21.2

**Plugin version (`steampipe plugin list`)**
0.33.0

**To reproduce**
Column is not available in the table, however it's described in the documentation:
[OCI API reference](https://docs.oracle.com/en-us/iaas/api/#/en/database/20160918/Database/)

**Expected behavior**
For each database, this column should show the status of the Management options for the database.
Possible values:

- Null (Database Management is not enabled)
- JSON that contains 2 fields: 
   - management_type : BASIC or ADVANCED
   - management_status : ENABLING, ENABLED, DISABLING, DISABLED, UPDATING, FAILED_ENABLING, FAILED_DISABLING, FAILED_UPDATING

**Additional context**
This column will provide more information about databases regarding OCI Database Management. This can be added to the OCI Insights mod to show:
- all databases that are managed by OCI Database Management
- all databases that are managed by OCI Databases Management but with a status other than "ENABLED"

**Comment by ParthaI** [comment]
Hello @hslange,

Thank you for highlighting this issue. Your engagement with Steampipe is truly valued.

To address the matter you've raised, we've initiated a [draft PR](https://github.com/turbot/steampipe-plugin-oci/pull/591), which incorporates all the columns that were previously missing in the table.

We would be grateful if you could test this out on the PR branch (`issue-589`) and share your feedback with us.

Here are the steps to try out the changes in the `issue-589` branch:
1. Clone the repository: `git clone https://github.com/turbot/steampipe-plugin-oci.git`
2. Navigate to the directory: `cd steampipe-plugin-oci`
3. Switch to the branch: `git checkout issue-589`
4. Execute the command: `make`
5. Run your query

Thank you!

**Comment by hslange** [comment]
Hi @ParthaI ,
Thank you very much for the quick implementation.
I tested it and it's working as expected.
results of a query to retrieve the database_management_options returns either:

- null, database management not enabled
- json field with the correct values for **managementStatus** and **managementType**

Please go ahead and push for PR.
Thanks again,
Herman

**Comment by ParthaI** [comment]
Hello @hslange, 
Thank you for thoroughly testing the PR and sharing your feedback on the changes. Your input is highly valued! 
I'll coordinate with our team to determine our subsequent actions. 👍
