### ISSUE TITLE
Table oci_file_storage_snapshot is misssing few columns

### ISSUE THREAD

**Issue by hslange** [turbot/steampipe-plugin-oci#590]
**Describe the bug**
The table **oci_file_storage_snapshot** is missing few columns, because is added by Oracle last year with the introduction of Filesystem Snapshot Policies.
The following columns are missing:
- filesystem_snapshot_policy_id
- snapshot_type (Values can be one of: USER, POLICY_BASED, REPLICATION)
- snapshot_time (The date and time the snapshot was taken, expressed in RFC 3339 timestamp format. This value might be the same or different from timeCreated depending on the some factors)

**Steampipe version (`steampipe -v`)**
v0.21.3

**Plugin version (`steampipe plugin list`)**
0.33.0

**To reproduce**
steampipe query
.inspect oci_file_storage_snapshot
compare with OCI documentation: [OCI Snapshot Reference](https://docs.oracle.com/en-us/iaas/api/#/en/filestorage/20171215/Snapshot/)

**Expected behavior**
Show all available data, including the Snapshot policy ID, Type and Time Created

**Additional context**
Snapshot policies are defined in a separate table. This table is missing in steampipe. See the documentation reference [here](https://docs.oracle.com/en-us/iaas/api/#/en/filestorage/20171215/FilesystemSnapshotPolicy/). 
For completeness, it would be nice to include a new table for the file systems snapshot policy as well (suggestion: oci_file_storage_snapshot_policy)

**Comment by ParthaI** [comment]
Hello @hslange,

Thank you for bringing to our attention the issue regarding the missing columns in the `oci_file_storage_snapshot` table. I've initiated a [PR](https://github.com/turbot/steampipe-plugin-oci/pull/592) to address this, where I've added the `snapshot_type` and `snapshot_time` columns. However, I have not included the `filesystem_snapshot_policy_id` column yet.

After reviewing the documentation you provided and examining the related Go SDK, I noted that our plugin currently utilizes SDK version [65.28.0](https://github.com/oracle/oci-go-sdk/blob/master/CHANGELOG.md#65280---2022-12-13), which does not return a value for `filesystem_snapshot_policy_id`. The support for **policy-based snapshots in the File Storage service** is introduced in SDK version [65.40.0](https://github.com/oracle/oci-go-sdk/blob/master/CHANGELOG.md#65400---2023-05-30).

However, upgrading to this SDK version involves navigating through breaking changes, as noted in the [CHANGELOG](https://github.com/oracle/oci-go-sdk/blob/master/CHANGELOG.md), which could impact other tables in our setup. We plan to include the `filesystem_snapshot_policy_id` column and introduce a new table, `oci_file_storage_snapshot_policy`, as part of our upgrade process in the future. 

Thank You!

**Comment by hslange** [comment]
Hi @ParthaI ,
Thanks for the response. It would make sense to upgrade the SDK first, before adding the filesystem_snapshot_policy_id column and oci_file_storage_snapshot_policy table.
This will also make it possible to implement another enhancement I created regarding Identity Domains in OCI, which was introduced in SDK after 65.28.0.
Please keep me updated when this upgrade is planned.
Thanks,
Herman
