### ISSUE TITLE
Fix `platform_config` column  in table oci_core_instance

### ISSUE THREAD

**Issue by khushboo9024** [turbot/steampipe-plugin-oci#595]
**Describe the bug**
`platform_config`  cloumn is coming null in table oci_core_instance.
We need to check whether secure boot is enabled or disabled. (Required for CIS V2.0.0)

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by ParthaI** [comment]
We are currently utilizing the [ListInstances](https://pkg.go.dev/github.com/oracle/oci-go-sdk/v65@v65.28.0/core#ComputeClient.ListInstances) API from the `github.com/oracle/oci-go-sdk/v65/core` Go Package to list instances in our environment. Our requirement includes retrieving [PlatformConfig](https://pkg.go.dev/github.com/oracle/oci-go-sdk/v65@v65.28.0/core#PlatformConfig) details provided by this API. However, we consistently receive a `null` value for the `PlatformConfig` attribute.

I have raised an issue with the SDK side addressing this issue. Issue ref: https://github.com/oracle/oci-go-sdk/issues/474
